# 1. Define the UART bus for RS485 communication
uart:
  - id: uart_bus
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600
    tx_enable_pin: GPIO4 # Pin to control DE/RE on the MAX485 adapter

# 2. Configure the Merrytek Radar component hub
external_components:
  - source:
      type: local
      path: custom_components

merrytek_radar:
  - uart_id: uart_bus
    update_interval: 10s 
    device_id: 0x0000 
    id: my_radar

# 3. Define all the entities for your sensor
binary_sensor:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: presence
    name: "Radar Presence"

sensor:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: light_level
    name: "Radar Light Level"
    
switch:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: led_indicator
    name: "Radar LED Indicator"
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: presence_detection_enable
    name: "Radar Presence Detection"
    
number:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: hold_time
    name: "Radar Hold Time"
    unit_of_measurement: "s"
    min_value: 3
    max_value: 7200
    step: 1
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: daylight_threshold
    name: "Radar Daylight Threshold"
    unit_of_measurement: "lx"
    min_value: 5
    max_value: 2000
    step: 5

select:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: sensitivity
    name: "Radar Sensitivity"
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: near_zone_shielding
    name: "Radar Near-Zone Shielding"

button:
  - platform: merrytek_radar
    merrytek_radar_id: my_radar
    type: factory_reset
    name: "Radar Factory Reset"